export enum ActionType {
    ANSWER_TRUE = 'ANSWER_TRUE',
    ANSWER_FALSE = 'ANSWER_FALSE',
    GET_QUESTIONS_LOADING = 'GET_QUESTIONS_LOADING',
    GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS',
    GET_QUESTIONS_ERROR = 'GET_QUESTIONS_ERROR',
}
